// Export list of all objects by their object ID

module.exports = {
	0: require('./enemies/goomba'),
	1: require('./enemies/koopa'),
	2: require('./enemies/piranhaplant'),
	3: require('./enemies/hammerbro'),
	4: require('./terrain/block'),
	5: require('./terrain/questionblock'),
	6: require('./terrain/hardblock'),
	7: require('./terrain/ground'),
	8: require('./items/coin'),
	9: require('./terrain/pipe'),
	10: require('./gizmos/trampoline'),
	11: require('./gizmos/lift'),
	12: require('./enemies/thwomp'),
	13: require('./gizmos/blaster'),
	14: require('./terrain/mushroomplatform'),
	15: require('./enemies/bobomb'),
	16: require('./terrain/semisolidplatform'),
	17: require('./terrain/bridge'),
	18: require('./gizmos/pswitch'),
	19: require('./gizmos/powblock'),
	20: require('./items/mushroom'),
	21: require('./terrain/donutblock'),
	22: require('./terrain/cloudblock'),
	23: require('./terrain/noteblock'),
	24: require('./gizmos/firebar'),
	25: require('./enemies/spiny'),
	26: null, // Ground Goal
	27: null, // Goal Pole
	28: require('./enemies/buzzybeetle'),
	29: require('./terrain/hiddenblock'),
	30: require('./enemies/lakitu'),
	31: require('./enemies/cloud'),
	32: require('./gizmos/banzaibill'),
	33: require('./items/oneup'),
	34: require('./items/fireflower'),
	35: require('./items/star'),
	36: require('./gizmos/lavalift'),
	37: null, // Ground Start
	38: null, // Start Sign
	39: require('./enemies/kamek'),
	40: require('./enemies/spiketop'),
	41: require('./enemies/boo'),
	42: require('./enemies/clowncar'),
	43: require('./terrain/spiketrap'),
	44: require('./items/powerup'),
	45: require('./items/specialentity'),
	46: require('./enemies/drybones'),
	47: require('./gizmos/cannon'),
	48: require('./enemies/blooper'),
	49: null, // Castle Bridge
	50: require('./enemies/hopchop'),
	51: require('./enemies/skipsqueak'),
	52: require('./enemies/wiggler'),
	53: require('./gizmos/conveyor'),
	54: require('./gizmos/burner'),
	55: require('./gizmos/door'),
	56: require('./enemies/cheepcheep'),
	57: require('./enemies/muncher'),
	58: require('./enemies/rockywrench'),
	59: require('./gizmos/rail'),
	60: require('./enemies/podoboo'),
	61: require('./enemies/chainchomp'),
	62: require('./enemies/bowser'),
	63: require('./terrain/iceblock'),
	64: require('./gizmos/vine'),
	65: require('./enemies/stingby'),
	66: require('./gizmos/arrowsign'),
	67: require('./gizmos/oneway'),
	68: require('./gizmos/grinder'),
	69: null, // Player
	70: require('./items/multicoin'),
	71: require('./terrain/semisolidplatform-3dw'),
	72: require('./enemies/koopacar'),
	73: null, // Toad
	74: require('./enemies/spike'),
	75: null, // Stone
	76: require('./gizmos/twister'),
	77: require('./enemies/boomboom'),
	78: require('./enemies/pokey'),
	79: require('./gizmos/pblock'),
	80: require('./gizmos/dashblock'),
	81: null, // Unused
	82: require('./gizmos/bumper'),
	83: require('./gizmos/spikepillar'),
	84: require('./gizmos/snakeblock'),
	85: require('./gizmos/trackblock'),
	86: require('./enemies/charvaargh'),
	87: require('./terrain/gentleslope'),
	88: require('./terrain/steepslope'),
	89: null, // Custom Scroll Waypoint
	90: require('./gizmos/checkpoint'),
	91: require('./gizmos/seasaw'),
	92: require('./items/pinkcoin'),
	93: require('./terrain/clearpipe'),
	94: require('./gizmos/slopedconveyor'),
	95: require('./gizmos/key'),
	96: require('./enemies/anttrooper'),
	97: require('./gizmos/warpbox'),
	98: require('./enemies/bowserjr'),
	99: require('./gizmos/onoffswitch'),
	100: require('./gizmos/onoffblock'),
	101: null, // Lava Editor
	102: require('./enemies/montymole'),
	103: require('./enemies/fishbones'),
	104: require('./enemies/angrysun'),
	105: require('./gizmos/claw'),
	106: require('./gizmos/tree'),
	107: require('./enemies/piranhacreeper'),
	108: require('./gizmos/blinkingblock'),
	109: null, // Sound Effect Icon
	110: require('./terrain/spikeblock'),
	111: null, // Unused
	112: require('./gizmos/crate'),
	113: require('./gizmos/mushroomtrampoline'),
	114: require('./enemies/porcupuffer'),
	115: null, // Goal Toadette
	116: require('./items/superhammer'),
	117: require('./enemies/bully'),
	118: require('./gizmos/icicle'),
	119: require('./gizmos/expandingblock'),
};